---

simulation_data_path: ~/.Data/nbody_simulations # DATASET PATH
experiments_dir: ~/.Data/Experiments/Nbody      # MODEL OUTPUTS
seed : 77743196
var_scope : params_{}

channels : [3, 32, 16, 8, 3]
#channels : [3, 32, 64, 128, 256, 64, 16, 8, 3]
#num_layer_W : 4  # weights per layer; 4 for shiftinv
#num_layer_W : 1  # weights per layer, SET
num_layer_W : 15
scalar_val : 0.002
restore : false

num_eval_samples: 200
num_iters: 2000
batch_size: 4
neighbors: 14
always_write_meta : false
model_tag: ''

z_idx :
    ZA  : [0]
    UNI : [10, 19]
dataset_type : ZA # Either ZA or UNI
